version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install

  build:
    commands:
      - npm run test

  post_build:
    commands:
      - npm run test

artifacts:
  files:
    - src/**/*
    - package.json
